
add_cus_dep('sage', 'sout', 0, 'makesout');
$hash_calc_ignore_pattern{'sage'} = '^( _st_.goboom| ?_st_.current_tex_line|print .SageT)';
sub makesout {
    system("python run-sagetex.py '$_[0].sage'");
}
